import argparse
import asyncio
import gc
import json
import re
import sys
import os
from typing import List, Dict, Any, Optional

from dotenv import load_dotenv
from mlx_lm import load, generate
from mcp.client.stdio import stdio_client, StdioServerParameters
from mcp.client.session import ClientSession

# Load environment variables (e.g. HF_TOKEN) from .env file
load_dotenv()

class MCPAgenticLoop:
    def __init__(self, model_name: str = "mlx-community/Qwen3-Coder-Next-80B-8bit", keep_in_memory: bool = False, persona_file: str = None):
        self.model_name = model_name
        self.model = None
        self.tokenizer = None
        self.keep_in_memory = keep_in_memory
        
        # Dictionary to store sessions for multiple servers
        self.sessions = {}
        self.available_tools = {}
        self.allowed_tool_names = None
        
        self.set_persona(persona_file)

    def set_persona(self, persona_file: str = None):
        """Dynamically hot-swaps the agent's persona and tool whitelist without reloading the model weights."""
        self.allowed_tool_names = None
        if persona_file and os.path.exists(persona_file):
            with open(persona_file, 'r') as f:
                content = f.read()
                
                if content.startswith('---'):
                    parts = content.split('---', 2)
                    if len(parts) >= 3:
                        frontmatter = parts[1]
                        self.system_prompt_template = parts[2].strip() + "\n\nYou have access to the following tools:\n{tool_descriptions}"
                        
                        import yaml
                        try:
                            meta = yaml.safe_load(frontmatter)
                            if meta and 'tools' in meta:
                                self.allowed_tool_names = meta['tools']
                        except Exception as e:
                            print(f"Warning parsing persona YAML: {e}")
                else:
                    self.system_prompt_template = content + "\n\nYou have access to the following tools:\n{tool_descriptions}"
        else:
            self.system_prompt_template = """You are an expert autonomous Full-Stack and DevOps engineer running locally on an M3 Ultra via Apple MLX.
You are highly capable of writing application code as well as Infrastructure as Code.

CRITICAL INSTRUCTIONS FOR FILE SEARCHING:
NEVER execute global wildcard searches (like `**/*.py` or `*`) when using file search tools. Doing so will dump thousands of virtual environment or node_modules files into your context window and crash you. ALWAYS restrict your searches to specific, narrow subdirectories (e.g., `src/`, `tests/`) or specific file names.

If you ever lose context of the overall goal or architecture, you should use your file tools to read `AGENT_PLAN.md` which contains the master specifications generated by the System Architect.

You have access to the following tools:
{tool_descriptions}

You must think step-by-step. 
To use a tool, output a JSON block wrapped in ```json ... ``` exactly like this:
```json
{{
  "tool": "tool_name",
  "kwargs": {{"param_name": "param_value"}}
}}
```

Wait for the tool result to be provided to you before continuing.
If you do not need to use a tool, output your final answer and explanation.
"""

    def _load_model(self):
        if self.model is None:
            print(f"Loading {self.model_name} into unified memory...")
            self.model, self.tokenizer = load(self.model_name)
            
    def _unload_model(self):
        if self.model is not None and not self.keep_in_memory:
            print(f"Unloading {self.model_name} to free unified memory...")
            del self.model
            del self.tokenizer
            self.model = None
            self.tokenizer = None
            gc.collect()

    async def generate_response(self, messages: List[Dict[str, str]]) -> str:
        self._load_model()
        prompt = self.tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )
        print("\nModel is generating (This may take longer if using a Thinking model)...")
        # Run generation in a separate thread so it doesn't block the async event loop
        # We increase max_tokens to 8000 because Thinking models use thousands of tokens for internal logic
        response = await asyncio.to_thread(
            generate,
            self.model,
            self.tokenizer,
            prompt=prompt,
            max_tokens=8000,
            verbose=False
        )
        
        # Intercept and strip <think> blocks (DeepSeek-R1 / QwQ format)
        think_match = re.search(r'<think>(.*?)</think>', response, re.DOTALL | re.IGNORECASE)
        if think_match:
            think_content = think_match.group(1).strip()
            print(f"[SYSTEM] Model generated {len(think_content.split())} words of internal thought process.")
            # Remove the think block from the final returned response
            response = re.sub(r'<think>.*?</think>', '', response, flags=re.DOTALL | re.IGNORECASE).strip()
            
        return response

    async def _compact_context(self, messages: List[Dict[str, str]]) -> List[Dict[str, str]]:
        """
        Multi-Dimensional Context Compaction: Prevents context rot by asking the LLM 
        to semantically summarize the older history into a dense state object.
        """
        # Ensure the model and tokenizer are loaded before we can count tokens
        self._load_model()
        
        # 1. Deterministic Token Counting
        # Convert the current message array into the exact string the LLM will see
        prompt_string = self.tokenizer.apply_chat_template(messages, tokenize=False)
        
        # Encode the string to get the exact token count
        # Note: Depending on the huggingface tokenizer version, encode() returns a list of integers
        token_ids = self.tokenizer.encode(prompt_string)
        current_token_count = len(token_ids)
        
        # Qwen3-80B has a 128k context window. We trigger compaction at 100k 
        # to leave plenty of room for the prompt and the generation output.
        MAX_CONTEXT_TOKENS = 100_000
        
        if current_token_count <= MAX_CONTEXT_TOKENS:
            # We are safe. No compaction needed.
            # (Optional: Print a debug statement if you want to track context growth)
            # print(f"[DEBUG] Current Context Size: {current_token_count}/{MAX_CONTEXT_TOKENS} tokens")
            return messages
            
        print(f"\n[SYSTEM] Context window critical ({current_token_count} tokens). Initiating Multi-Dimensional Compaction...")
        
        # We preserve the System Prompt and the initial User Prompt (indices 0 and 1)
        # We preserve the 4 most recent messages (recent context)
        # We compact everything in the middle.
        core_messages = messages[:2]
        recent_messages = messages[-4:]
        messages_to_compact = messages[2:-4]
        
        # Convert the middle messages into a string payload
        history_text = ""
        for msg in messages_to_compact:
            history_text += f"\n--- {msg['role'].upper()} ---\n{msg['content']}"
            
        compaction_prompt = f"""You are a Context Compaction Agent.
Analyze the following execution history and summarize it into a strict JSON object to preserve the critical state for the next agent.
Your JSON must have the following keys:
- "completed_actions": A list of strings describing what was actually done (e.g., "Wrote 45 lines to auth.py").
- "active_system_state": A list of strings describing current reality (e.g., "Postgres running on port 5432").
- "unresolved_threads": A list of strings detailing what still needs to be done or what errors are pending.
- "key_decisions": A list of strings explaining why certain choices were made.

History to compact:
{history_text}

Output ONLY the JSON block wrapped in ```json ... ``` tags."""

        compaction_messages = [{"role": "user", "content": compaction_prompt}]
        summary_response = await self.generate_response(compaction_messages)
        
        # Extract the JSON summary
        json_match = re.search(r'```json\s*(.*?)\s*```', summary_response, re.DOTALL | re.IGNORECASE)
        if json_match:
            summary_content = json_match.group(1).strip()
        else:
            summary_content = summary_response # Fallback
            
        compacted_message = {
            "role": "assistant",
            "content": f"[SYSTEM: CONTEXT COMPACTED]\nPrevious steps have been summarized to preserve memory:\n```json\n{summary_content}\n```"
        }
        
        # Rebuild the message history: Core -> Summary -> Recent
        new_messages = core_messages + [compacted_message] + recent_messages
        print("[SYSTEM] Compaction complete. Context pristine.")
        return new_messages

    def parse_tool_call(self, response: str) -> Optional[Dict[str, Any]]:
        json_match = re.search(r'```json\s*(.*?)\s*```', response, re.DOTALL)
        if json_match:
            try:
                parsed = json.loads(json_match.group(1))
                if isinstance(parsed, dict) and "tool" in parsed:
                    return parsed
            except json.JSONDecodeError:
                return None
        return None

    def _format_tools(self) -> str:
        descriptions = []
        for server_name, tools in self.available_tools.items():
            server_has_tools = False
            server_tools_str = [f"\n--- Tools from {server_name} ---"]
            
            for tool in tools:
                if self.allowed_tool_names is None or tool.name in self.allowed_tool_names:
                    server_has_tools = True
                    desc = f"- **{tool.name}**: {tool.description}\n  Schema: {json.dumps(tool.inputSchema)}"
                    server_tools_str.append(desc)
                    
            if server_has_tools:
                descriptions.extend(server_tools_str)
                
        return "\n".join(descriptions)

    async def setup_mcp_servers(self):
        """Initializes all required MCP servers."""
        allowed_dir = os.path.abspath(".")
        db_path = os.path.join(allowed_dir, "agent.db")
        
        # 1. Filesystem Server (Node/npx)
        fs_params = StdioServerParameters(
            command="npx",
            args=["-y", "@modelcontextprotocol/server-filesystem", allowed_dir],
        )
        
        # 2. Git Server (Python/pip)
        git_params = StdioServerParameters(
            command="python3",
            args=["-m", "mcp_server_git", "--repository", allowed_dir],
        )
        
        # 3. SQLite Server (Python/pip)
        sqlite_params = StdioServerParameters(
            command="mcp-server-sqlite",
            args=["--db-path", db_path],
        )
        
        # 4. Fetch Server (Python/pip) - Better for direct RAG than Puppeteer
        fetch_params = StdioServerParameters(
            command="mcp-server-fetch",
            args=[],
        )
        
        # 5. Memory Server (Node/npx) - For multi-agent context sharing
        memory_params = StdioServerParameters(
            command="npx",
            args=["-y", "@modelcontextprotocol/server-memory"],
        )
        
        # 6. Custom Bash Server (Python) - For CI/CD and Testing
        bash_params = StdioServerParameters(
            command="python3",
            args=["mcp_server_bash.py"],
        )

        servers = {
            "Filesystem": fs_params,
            "Git": git_params,
            "SQLite": sqlite_params,
            "Fetch": fetch_params,
            "Memory": memory_params,
            "Bash": bash_params
        }

        self.server_configs = servers

    async def execute_tool_call(self, tool_name: str, tool_kwargs: dict) -> str:
        target_server_name = None
        
        for server_name, tools in self.available_tools.items():
            if any(t.name == tool_name for t in tools):
                target_server_name = server_name
                break
                
        if not target_server_name:
            raise ValueError(f"Tool '{tool_name}' not found in any connected server.")

        params = self.server_configs[target_server_name]
        
        async with stdio_client(params) as (read, write):
            async with ClientSession(read, write) as session:
                await session.initialize()
                result = await session.call_tool(tool_name, arguments=tool_kwargs)
                return "\n".join([c.text for c in result.content if hasattr(c, 'text')])

    async def run(self, user_prompt: str):
        print(f"Starting Multi-Server MCP Agentic Loop...")
        
        await self.setup_mcp_servers()
        
        print("Discovering tools from servers...")
        for name, params in self.server_configs.items():
            try:
                async with stdio_client(params) as (read, write):
                    async with ClientSession(read, write) as session:
                        await session.initialize()
                        tools_response = await session.list_tools()
                        self.available_tools[name] = tools_response.tools
                        print(f"[{name}] discovered {len(tools_response.tools)} tools.")
            except Exception as e:
                print(f"Failed to connect to {name} server: {e}")

        system_prompt = self.system_prompt_template.replace(
            "{tool_descriptions}", self._format_tools()
        )
        
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"Task: {user_prompt}"}
        ]
        
        max_iterations = 10
        
        for i in range(max_iterations):
            print(f"\n--- Iteration {i+1} ---")
            
            # Apply context compaction before generation
            messages = await self._compact_context(messages)
            
            response = await self.generate_response(messages)
            print(f"Agent Output:\n{response}")
            messages.append({"role": "assistant", "content": response})
            
            tool_call = self.parse_tool_call(response)
            
            if tool_call:
                tool_name = tool_call.get("tool")
                tool_kwargs = tool_call.get("kwargs", {})
                print(f"\n[Executing Tool via MCP]: {tool_name} with args {tool_kwargs}")
                
                try:
                    result_text = await self.execute_tool_call(tool_name, tool_kwargs)
                    print(f"[Tool Result]:\n{result_text[:1000]}... (truncated if long)")
                    messages.append({"role": "user", "content": f"Tool '{tool_name}' result:\n{result_text}"})
                except Exception as e:
                    error_msg = f"Error executing tool '{tool_name}': {str(e)}"
                    print(f"[Tool Error]: {error_msg}")
                    messages.append({"role": "user", "content": error_msg})
            else:
                print("\n[Finished]: No more tool calls. Task complete.")
                break
                
        self._unload_model()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run the MLX Multi-Server Agentic Loop.")
    parser.add_argument("--prompt", type=str, default="Use the 'fetch' tool to read https://example.com and summarize it.",
                        help="The initial user prompt.")
    parser.add_argument("--model", type=str, default="mlx-community/Qwen2.5-72B-Instruct-8bit",
                        help="HuggingFace model ID (must be an MLX format model).")
    parser.add_argument("--persona", type=str, default=None,
                        help="Path to a markdown file defining the agent's persona and tool whitelist.")
    
    args = parser.parse_args()
    agent = MCPAgenticLoop(model_name=args.model, persona_file=args.persona)
    
    try:
        asyncio.run(agent.run(user_prompt=args.prompt))
    except KeyboardInterrupt:
        print("\nExiting...")
        agent._unload_model()
        sys.exit(0)
