[mypy]
python_version = 3.8
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
no_implicit_reexport = true
no_strict_optional = true
show_error_codes = true
