#!/usr/bin/env python3
"""
Initialize .docs/ directory structure for documentation pipeline.

Requires: Python 3.9+ (for is_relative_to())

Usage:
    python init-docs-structure.py [tier] [project_name]

Tiers:
    essential     - 2 folders (requirements, architecture) - 3 documents
    standard      - 4 folders (+ api, planning) - 4 documents
    comprehensive - all 10 phase folders - 63 documents

Examples:
    python init-docs-structure.py essential MyProject
    python init-docs-structure.py standard PaymentService
    python init-docs-structure.py comprehensive TradingPlatform
"""

import os
import sys
from datetime import datetime
from pathlib import Path

# Runtime version check
if sys.version_info < (3, 9):
    sys.exit("Error: Python 3.9+ required (for is_relative_to())")


# Directory structure by tier
ESSENTIAL_DIRS = [
    "requirements",
    "architecture",
]

STANDARD_DIRS = ESSENTIAL_DIRS + [
    "api",
    "planning",
]

COMPREHENSIVE_DIRS = [
    "conception",      # Phase 0
    "requirements",    # Phase 1
    "architecture",    # Phase 2
    "api",
    "ui",
    "planning",        # Phase 3
    "testing",         # Phase 4
    "reviews",         # Phase 4
    "release",         # Phase 5
    "operations",      # Phase 6
    "support",         # Phase 7
    "support/incidents",
    "maintenance",     # Phase 8
    "retirement",      # Phase 9
    "architecture/decisions",  # ADRs
]

TIER_MAPPING = {
    "essential": ESSENTIAL_DIRS,
    "standard": STANDARD_DIRS,
    "comprehensive": COMPREHENSIVE_DIRS,
}


def create_gitignore(docs_path: Path) -> None:
    """Create .gitignore to exclude .docs from version control."""
    gitignore_path = docs_path.parent / ".gitignore"

    gitignore_entry = ".docs/"

    if gitignore_path.exists():
        content = gitignore_path.read_text()
        if gitignore_entry not in content:
            with open(gitignore_path, "a") as f:
                f.write(f"\n# Documentation pipeline artifacts\n{gitignore_entry}\n")
            print(f"  Updated: {gitignore_path}")
    else:
        gitignore_path.write_text(f"# Documentation pipeline artifacts\n{gitignore_entry}\n")
        print(f"  Created: {gitignore_path}")


def create_readme(docs_path: Path, project_name: str, tier: str) -> None:
    """Create README.md in .docs/ directory."""
    readme_path = docs_path / "README.md"

    content = f"""# {project_name} Documentation

**Generated:** {datetime.now().isoformat()}
**Tier:** {tier.capitalize()}

## Directory Structure

This directory contains internal project documentation generated by the documentation-pipeline.

**Note:** This directory is gitignored. Documentation here is for development reference.

## Phases

| Phase | Directory | Description |
|-------|-----------|-------------|
| 0 | conception/ | Business case, project charter |
| 1 | requirements/ | Requirements, user stories |
| 2 | architecture/ | Architecture, system design |
| 3 | planning/ | Implementation plan, standards |
| 4 | testing/, reviews/ | Test strategy, code review |
| 5 | release/ | Deployment, changelog |
| 6 | operations/ | Monitoring, runbooks |
| 7 | support/ | Incident response, troubleshooting |
| 8 | maintenance/ | Technical debt, upgrades |
| 9 | retirement/ | Migration, decommission |

## Usage

Generate documentation:
```bash
# Using skill
"Create [tier] documentation for {project_name}"

# Using commands
/doc-lifecycle {project_name} --full
/doc-phase-2-architecture {project_name}
```
"""
    readme_path.write_text(content)
    print(f"  Created: {readme_path}")


def create_structure(tier: str, project_name: str, base_path: str = ".") -> None:
    """Create .docs/ directory structure for the specified tier."""

    if tier not in TIER_MAPPING:
        print(f"Error: Unknown tier '{tier}'")
        print(f"Available tiers: {', '.join(TIER_MAPPING.keys())}")
        sys.exit(1)

    # Security: Validate base_path to prevent path traversal
    resolved_base = Path(base_path).resolve()
    cwd = Path.cwd().resolve()

    # Ensure base_path is under current working directory or is cwd itself
    # Use is_relative_to() for safe path comparison (avoids /home/user matching /home/username)
    try:
        is_under_cwd = resolved_base.is_relative_to(cwd)
    except ValueError:
        is_under_cwd = False

    if not (is_under_cwd or resolved_base == cwd):
        print(f"Error: base_path must be under current working directory")
        print(f"  Current directory: {cwd}")
        print(f"  Requested path: {resolved_base}")
        sys.exit(1)

    docs_path = resolved_base / ".docs"
    directories = TIER_MAPPING[tier]

    # Security: Reject if .docs is a symlink
    if docs_path.exists() and docs_path.is_symlink():
        print(f"Error: Security - .docs/ is a symlink, which is not allowed")
        sys.exit(1)

    print(f"\nInitializing .docs/ structure for '{project_name}' ({tier} tier)")
    print(f"Base path: {docs_path.absolute()}\n")

    # Create main .docs directory
    docs_path.mkdir(exist_ok=True)
    print(f"  Created: {docs_path}/")

    # Create subdirectories
    for dir_name in directories:
        dir_path = docs_path / dir_name
        # Security: Skip if path is a symlink
        if dir_path.exists() and dir_path.is_symlink():
            print(f"  Skipped: {dir_path}/ (symlink - security risk)")
            continue
        dir_path.mkdir(parents=True, exist_ok=True)
        print(f"  Created: {dir_path}/")

    # Create supporting files
    create_readme(docs_path, project_name, tier)
    create_gitignore(docs_path)

    print(f"\n[OK] Structure created successfully!")
    print(f"   Directories: {len(directories)}")
    print(f"   Tier: {tier}")
    print(f"\nNext steps:")
    print(f"  1. Generate requirements: /doc-phase-1-requirements {project_name}")
    print(f"  2. Generate architecture: /doc-phase-2-architecture {project_name}")


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    tier = sys.argv[1].lower()
    project_name = sys.argv[2] if len(sys.argv) > 2 else "Project"
    base_path = sys.argv[3] if len(sys.argv) > 3 else "."

    create_structure(tier, project_name, base_path)


if __name__ == "__main__":
    main()
